- hosts: all

  become: yes
  become_method: sudo

  tasks:
    - name: Create web root
      file:
        dest: /var/www
        state: directory
        owner: '{{ host_user }}'
        group: '{{ host_user }}'
        mode: 0755

    - name: Copy site to server
      synchronize:
        src: ../site/
        dest: /var/www
        delete: yes

    - name: Setup site owner
      file:
        dest: /var/www
        owner: '{{ host_user }}'
        group: '{{ host_user }}'
        recurse: yes
