name: Deploy to GitHub pages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm ci
    - name: Build site
      run: npm run build
    - name: Publish content to GitHub Pages
      uses: andre487/publish-to-orphan-gh-pages@v1.2.1
      with:
        deploy_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
