name: Deploy to GitHub pages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install dependencies
      run: npm ci
    - name: Build site
      run: npm run build
    - name: Publish content to GitHub Pages
      uses: andre487/publish-to-orphan-gh-pages@024d11772eaa7348d04cbaf1d3881a8bfaf3d5cd
      with:
        src_dir: ./build
        dest_dir: .
        branch: gh-pages
        deploy_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        deploy_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
        important_files: '["CNAME", "custom-file.html"]'
        debug: true
